import { ArrowIcon } from "../arrow-icon";
import type { Metadata } from "next";
import { EngineeringPanel, ContactBand, SiteFooter, SiteHeader } from "../components";
import { ServiceCards, ProjectCards } from "./shared";
export const metadata: Metadata = {
 title:"Проектирование инженерных систем — направления и цены | ПЛАНКОД",
 description:"Проектирование отопления, вентиляции, кондиционирования, ВК, электроснабжения и ИТП. Состав работ, стартовые цены и примеры проектной документации.",
 alternates:{canonical:"/design.html"},openGraph:{images:["/og.png"]},twitter:{images:["/og.png"]}
};
export default function DesignPage(){return <main className="engineering-page page-design"><SiteHeader active="design" />
<section className="portfolio-hero shell" id="top"><div className="portfolio-copy panel"><span className="micro-label">ПРОЕКТИРОВАНИЕ / ПЛАНКОД</span><h1>Инженерные системы.<br/><em>Согласованный проект.</em></h1><p>От отдельного раздела до комплекса инженерных решений. Разрабатываем расчёты, планы, схемы и спецификации для новых и существующих зданий.</p><a className="interior-cta" href="#contact" data-goal="discuss_service">Обсудить проект <span><ArrowIcon direction="up-right" /></span></a><div className="portfolio-facts"><span><b>П и Р</b> стадии по заданию</span><span><b>ОВиК · ВК · ЭОМ</b> согласованные разделы</span><span><b>Revit / BIM</b> моделирование и координация</span></div></div><EngineeringPanel variant="design" /></section>
<section className="page-section shell" id="directions"><div className="page-heading"><span>01 / НАПРАВЛЕНИЯ</span><h2>Выберите<br/><em>свою задачу.</em></h2><p>Стартовые цены на проектирование. Итоговая стоимость зависит от объекта, стадии и согласованного состава работ.</p></div><ServiceCards /></section>
<section className="service-context"><div className="shell"><span className="micro-label">02 / ОБЪЕКТ И УСЛОВИЯ</span><h2>Новое строительство.<br/>Реконструкция.<br/><em>Капитальный ремонт.</em></h2><p>Учитываем назначение помещений, технологическое оборудование, существующие коммуникации и ограничения размещения новых систем.</p></div></section>
<section className="page-section shell"><div className="page-heading"><span>03 / РЕЗУЛЬТАТ</span><h2>От исходных данных<br/><em>к документации.</em></h2><p>Состав фиксируем до начала разработки. Стадии П и Р, BIM-модель, согласования и сопровождение определяем по заданию.</p></div><div className="service-deliverables">{["Расчёты нагрузок и параметров систем","Планы, схемы и проектные узлы","Спецификации оборудования и материалов","Координация инженерных разделов"].map((x,i)=><article className="panel" key={x}><span>0{i+1}</span><h3>{x}</h3></article>)}</div></section>
<section className="page-section shell" id="portfolio"><div className="page-heading"><span>04 / ПРИМЕРЫ ПРОЕКТОВ</span><h2>Задачи и решения<br/><em>в чертежах.</em></h2><p>Выберите направление и рассмотрите примеры проектных решений. Идентифицирующие сведения не публикуем.</p></div><ProjectCards filter /></section>
<section className="service-price-note shell"><h2>Как определяется стоимость</h2><p>Учитываем площадь и назначение объекта, состав разделов, стадию П или Р, исходную документацию, необходимость обследования, моделирования и согласований. Для сложных объектов и реконструкции готовим индивидуальное предложение по ТЗ.</p></section>
<ContactBand engineering context="Интересует: проектирование инженерных систем." eyebrow="ОБСУДИТЬ ЗАДАЧУ" title={"Расскажите об объекте.\nОпределим состав проекта."}/><SiteFooter /></main>;}
